# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.define :local do |vm_config|
    vm_config.vm.box = "precise64"
    vm_config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    vm_config.vm.host_name = "local"
    vm_config.vm.network :hostonly, "192.168.1.10"
    vm_config.vm.provision :shell, :path => "_vagrant/setup_rpyc.sh"
    vm_config.vm.forward_port 18812, 10001
  end

  config.vm.define :remote do |vm_config|
    vm_config.vm.box = "precise64"
    vm_config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    vm_config.vm.host_name = "remote"
    vm_config.vm.provision :shell, :path => "_vagrant/setup_rpyc.sh"
    vm_config.vm.provision :shell, :path => "_vagrant/setup_netem.sh"
    vm_config.vm.network :hostonly, "192.168.1.11"
    vm_config.vm.forward_port 18812, 10002
  end

end
